### ISSUE TITLE
No prompt to download better-sqlite3 binary

### ISSUE THREAD

**Issue by huachuman** [PKM-er/obsidian-zotlit#181]
Hi I don't think I ever got the prompt to download the binary and haven't been able to find where on github to find the node.gz file

**Comment by aidenlx** [comment]
are you sure the plugin is enabled? Any errors in obsidian's developer console?

**Comment by huachuman** [comment]
Yes, it's enabled.

```
plugin:zotlit:6` [2023-09-10T07:19:54.784] [INFO] obsidian-zotero:main - loading ZotLit
plugin:zotlit:299 Uncaught (in promise) Error: Setting tab is not mounted
    at #e (plugin:zotlit:299:212212)
    at cs.display (plugin:zotlit:299:212646)
    at cs.display (plugin:zotlit:299:220093)
    at SettingsSearch.getTabResources (plugin:settings-search:228:15)
    at t.eval (plugin:settings-search:264:16)
    at t.wrapper [as addSettingTab] (plugin:settings-search:59:20)
    at t.addSettingTab (app.js:1:2024820)
    at le.onload (plugin:zotlit:299:222478)
    at e.load (app.js:1:720143)
    at e.<anonymous> (app.js:1:2031659)
plugin:zotlit:6 [2023-09-10T07:19:54.964] [INFO] obsidian-zotero:main - Server is listening at 127.0.0.1:9091
3cfededc-3f55-4755-bc34-3b208d6565fb:16 [2023-09-10T07:19:54.967] [INFO] obsidian-zotero:db-worker - Better BibTex database not enabled, skipping...
3cfededc-3f55-4755-bc34-3b208d6565fb:222 
Map(0)
3cfededc-3f55-4755-bc34-3b208d6565fb:16 [2023-09-10T07:19:54.968] [INFO] obsidian-zotero:db-worker - Finished reading main Zotero database for index
3cfededc-3f55-4755-bc34-3b208d6565fb:16 [2023-09-10T07:19:54.968] [INFO] obsidian-zotero:db-worker - Library citation index initialized
plugin:zotlit:6 [2023-09-10T07:19:54.969] [INFO] obsidian-zotero:main - ZoteroDB Initialization complete.
```

**Comment by aidenlx** [comment]
It should be working now, if the binary is not installed there would be errors in console. Maybe you’ve installed it before?
