### ISSUE TITLE
Zotero7 beta.46版本无法导入包含注释的文献笔记，报错：Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'renderColored')

### ISSUE THREAD

**Issue by biganji** [PKM-er/obsidian-zotlit#235]
没有注释笔记的文章可正常导出
具体报错：Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'renderColored')
    at Object.replacement (plugin:zotlit:329:37586)
    at k.D (turndown.js:2:9551)
    at turndown.js:2:9210
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9059)
    at k.D (turndown.js:2:9459)
    at turndown.js:2:9210
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9059)
    at k.D (turndown.js:2:9459)
    at turndown.js:2:9210
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9059)
    at k.turndown (turndown.js:2:10070)
    at ad.turndown (plugin:zotlit:329:40315)
    at ad.normalizeNotes (plugin:zotlit:329:40194)
    at async $b.createNoteForDocItemFull (plugin:zotlit:329:30157)
    at async Fb (plugin:zotlit:329:26917)

**Comment by Zhixiaz** [comment]
Zotero 6.0.30同样出现该问题，请问你解决了吗

**Comment by GritYearner** [comment]
我也出现了这个问题，在zotero的笔记中把注释颜色隐藏就好了

**Comment by GritYearner** [comment]
> Zotero 6.0.30同样出现该问题，请问你解决了吗

我也出现了这个问题，在zotero的笔记中把注释颜色隐藏就好了

**Comment by Zhixiaz** [comment]
> > Zotero 6.0.30同样出现该问题，请问你解决了吗
> 
> 我也出现了这个问题，我试了试把zotero的笔记中把注释颜色隐藏就可以正常导入了

谢谢，解决了
