### ISSUE TITLE
Error creating note when Zotero Note is available

### ISSUE THREAD

**Issue by misea** [PKM-er/obsidian-zotlit#257]
I have several items that have highlights and notes in Zotero where if I try to do "Create Literature Notes" I get an error in the Obsidian console and Obsidian comes to the front, but does not have a note. Strangely if I delete the *Zotero* note attached to the item, the error no longer appears and the PDF annotations are imported. I have no idea what is causing it, and I have tried to reproduce, but haven't figured out the simple case.

```
Unexpected annotation data {
  attachmentURI: 'http://zotero.org/users/429318/items/S456NKV7',
  pageLabel: '110',
  position: { pageIndex: 4, rects: [ [Array], [Array], [Array], [Array] ] },
  citationItem: {
    uris: [ 'http://zotero.org/users/429318/items/HUW4RNM7' ],
    locator: '110'
  }
} nh(1) [
  co {
    code: 'missing',
    path: We(1) [ 'annotationKey' ],
    data: undefined,
    source: undefined,
    writers: {
      mustBe: [Function: mustBe],
      writeReason: [Function: writeReason],
      addContext: [Function: cI]
    },
    parts: undefined
  },
  byPath: {
    annotationKey: co {
      code: 'missing',
      path: [We],
      data: undefined,
      source: undefined,
      writers: [Object],
      parts: undefined
    }
  },
  count: 1
]
```

**Comment by veale** [comment]
I have a related error, as it seems when a standalone note is attached to an item in Zotero, you cannot cite that item — pressing return in the markdown citation window does nothing.

**Comment by Katherine923-creator** [comment]
ME TOOOOOO！！！！！

**Comment by unlsycn** [comment]
The same

**Comment by Wizard-one** [comment]
I have same issue too, I think is same as #237.  

In note have a lot of annotation link to origin PDF, unlink every annotation seen impossible. 

My environment:

- win11
- Obsidian v1.6.5 installer version v1.5.12 
- zotlit version 1.1.5
- zotero: version => 6.0.36, platform => Win32, oscpu => Windows NT 10.0; 

This is my log
```
plugin:zotlit:6 [2024-07-16T15:04:54.073] [ERROR] obsidian-zotero:main - Unexpected annotation data {
  attachmentURI: 'http://zotero.org/users/10022128/items/PTG8WAI5',
  pageLabel: '112',
  position: { pageIndex: 2, rects: [ [Array] ] },
  citationItem: {
    uris: [ 'http://zotero.org/users/10022128/items/JRVLZFVA' ],
    locator: '112'
  }
} nh(1) [
  co {
    code: 'missing',
    path: We(1) [ 'annotationKey' ],
    data: undefined,
    source: undefined,
    writers: {
      mustBe: [Function: mustBe],
      writeReason: [Function: writeReason],
      addContext: [Function: lI]
    },
    parts: undefined
  },
  byPath: {
    annotationKey: co {
      code: 'missing',
      path: [We],
      data: undefined,
      source: undefined,
      writers: [Object],
      parts: undefined
    }
  },
  count: 1
]
plugin:zotlit:363 Uncaught (in promise) Error: Unexpected annotation data: annotationKey must be defined
    at yM (plugin:zotlit:363:388)
    at Object.replacement (plugin:zotlit:359:39872)
    at k.D (turndown.js:2:9551)
    at turndown.js:2:9210
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9059)
    at k.D (turndown.js:2:9459)
    at turndown.js:2:9210
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9059)
    at k.D (turndown.js:2:9459)
    at turndown.js:2:9210
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9059)
    at k.D (turndown.js:2:9459)
    at turndown.js:2:9210
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9059)
    at k.turndown (turndown.js:2:10070)
    at ud.turndown (plugin:zotlit:359:40322)
    at uM (plugin:zotlit:359:24823)
yM @ plugin:zotlit:363
replacement @ plugin:zotlit:359
D @ turndown.js:2
(anonymous) @ turndown.js:2
b @ turndown.js:2
D @ turndown.js:2
(anonymous) @ turndown.js:2
b @ turndown.js:2
D @ turndown.js:2
(anonymous) @ turndown.js:2
b @ turndown.js:2
D @ turndown.js:2
(anonymous) @ turndown.js:2
b @ turndown.js:2
turndown @ turndown.js:2
turndown @ plugin:zotlit:359
uM @ plugin:zotlit:359
await in uM (async)
callback @ plugin:zotlit:359
RK @ app.js:1
e.executeCommand @ app.js:1
eval @ plugin:obsidian-kanban:67
o @ plugin:obsidian-kanban:33
e.executeCommandById @ app.js:1
onChooseSuggestion @ plugin:darlal-switcher-plus:4117
onChooseSuggestion @ plugin:darlal-switcher-plus:4824
onChooseSuggestion @ plugin:darlal-switcher-plus:5591
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
(anonymous) @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1

```

**Comment by aidenlx** [comment]
Note creation now handles a Zotero note attached to an item cleanly: v2 links to it from the literature note, so the error you hit when a Zotero note was present shouldn't happen anymore.

v2 beta is available now: https://zotlit.aidenlx.site/docs/install-zotlit
Migration guide: https://zotlit.aidenlx.site/docs/how-to/migrate-from-v1
