### ISSUE TITLE
cannot create literature note(s), uploaded debug infos

### ISSUE THREAD

**Issue by CaoKang-David** [PKM-er/obsidian-zotlit#268]
when i right click create literature notes, there is no respond in obsidian.
**the debug infos are as follow:**
f8d0c488-a8c2-4047-9917-6ad5f774f7d4:1 [2023-11-24T12:45:08.515] [DEBUG] obsidian-zotero:db-worker - Reading Zotero database for attachments of item 56363
f8d0c488-a8c2-4047-9917-6ad5f774f7d4:1 [2023-11-24T12:45:08.516] [DEBUG] obsidian-zotero:db-worker - Finished reading Zotero database for attachments of item 56363, count: 1
f8d0c488-a8c2-4047-9917-6ad5f774f7d4:1 [2023-11-24T12:45:08.516] [DEBUG] obsidian-zotero:db-worker - Reading Zotero database for notes of literature 56363
f8d0c488-a8c2-4047-9917-6ad5f774f7d4:1 [2023-11-24T12:45:08.516] [DEBUG] obsidian-zotero:db-worker - Finished reading Zotero database for notes of literature 56363, count: 1
plugin:zotlit:6 [2023-11-24T12:45:08.518] [ERROR] obsidian-zotero:main - Unexpected citation data { citationItems: [ { uris: [Array], locator: '6' } ], properties: {} } nh(1) [
  co {
    code: 'regex',
    path: We(4) [ 'citationItems', '0', 'uris', '0' ],
    data: 'http://zotero.org/users/2896393/items/undefined5TJFH7SR',
    source: '/^https?:\\/\\/zotero\\.org\\/.*\\/items\\/([A-Z\\d]+)$/',
    writers: {
      mustBe: [Function: mustBe],
      writeReason: [Function: ao],
      addContext: [Function: cI]
    },
    parts: undefined
  },
  byPath: {
    'citationItems/0/uris/0': co {
      code: 'regex',
      path: [We],
      data: 'http://zotero.org/users/2896393/items/undefined5TJFH7SR',
      source: '/^https?:\\/\\/zotero\\.org\\/.*\\/items\\/([A-Z\\d]+)$/',
      writers: [Object],
      parts: undefined
    }
  },
  count: 1
]
plugin:zotlit:363 Uncaught (in promise) Error: Unexpected citation data: citationItems/0/uris/0 must be a string matching /^https?:\/\/zotero\.org\/.*\/items\/([A-Z\d]+)$/ (was 'http://zotero.org/users/2896393/items/undefined5TJFH7SR')
    at QX (plugin:zotlit:363:195)
    at Object.replacement (plugin:zotlit:359:39544)
    at k.D (turndown.js:2:9551)
    at turndown.js:2:9210
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9059)
    at k.D (turndown.js:2:9459)
    at turndown.js:2:9210
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9059)
QX @ plugin:zotlit:363
replacement @ plugin:zotlit:359
D @ turndown.js:2
(anonymous) @ turndown.js:2
b @ turndown.js:2
D @ turndown.js:2
(anonymous) @ turndown.js:2
b @ turndown.js:2
D @ turndown.js:2
(anonymous) @ turndown.js:2
b @ turndown.js:2
D @ turndown.js:2
(anonymous) @ turndown.js:2
b @ turndown.js:2
D @ turndown.js:2
(anonymous) @ turndown.js:2
b @ turndown.js:2
D @ turndown.js:2
(anonymous) @ turndown.js:2
b @ turndown.js:2
turndown @ turndown.js:2
turndown @ plugin:zotlit:359
normalizeNotes @ plugin:zotlit:359
eval @ plugin:zotlit:359
await in eval (async)
callback @ plugin:zotlit:359
rj @ app.js:1
t.onChooseItem @ app.js:1
t.onChooseSuggestion @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
(anonymous) @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1

**Comment by aidenlx** [comment]
v2 validates each step of note creation and shows a specific, visible message the moment something goes wrong, so this kind of silent freeze shouldn't happen anymore.

v2 beta is available now: https://zotlit.aidenlx.site/docs/install-zotlit
Migration guide: https://zotlit.aidenlx.site/docs/how-to/migrate-from-v1
