### ISSUE TITLE
I can‘t add citations form zotero. detail as following.

### ISSUE THREAD

**Issue by niecailong** [PKM-er/obsidian-zotlit#272]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'renderColored')
    at Object.replacement (plugin:zotlit:359:37593)
    at k.D (turndown.js:2:9551)
    at turndown.js:2:9210
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9059)
    at k.D (turndown.js:2:9459)
    at turndown.js:2:9210
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9059)
    at k.D (turndown.js:2:9459)
    at turndown.js:2:9210
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9059)
    at k.D (turndown.js:2:9459)
    at turndown.js:2:9210
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9059)
    at k.D (turndown.js:2:9459)
    at turndown.js:2:9210
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9059)
    at k.turndown (turndown.js:2:10070)
    at ud.turndown (plugin:zotlit:359:40322)
    at ud.normalizeNotes (plugin:zotlit:359:40201)
    at eval (plugin:zotlit:351:953)
    at async Qf (plugin:zotlit:351:891)
    at async ib (plugin:zotlit:351:2337)

**Comment by xiaojun678** [comment]
yes, i have the same problem

**Comment by niecailong** [comment]
I found this reseson of problem. as fllowlling 
![image](https://github.com/PKM-er/obsidian-zotlit/assets/75868761/c4c84f18-2248-434d-b8d3-b43d0599b2fb)

A reference can not be created successfully in the presence of the note in project。

**Comment by impermanD** [comment]
把标注文档中的颜色清理后就可用了，不知道什么原因

**Comment by niecailong** [comment]
> 控制中显示 同样的报错，在zotero中把标注文档中的颜色清理后就可用了，不知道什么原因。

不太懂你的意思，我的标注文档中没有使用带颜色字体和荧光标记。但仍旧报这个错误

**Comment by niecailong** [comment]
> 控制中显示 同样的报错，在zotero中把标注文档中的颜色清理后就可用了，不知道什么原因。

主要是，我没有找到颜色清理的选项在哪里。

**Comment by niecailong** [comment]
> > 控制中显示 同样的报错，在zotero中把标注文档中的颜色清理后就可用了，不知道什么原因。
> 
> 主要是，我没有找到颜色清理的选项在哪里。

我现在对标注中所有文字去格式化后完成了同步。

**Comment by SimonJarry** [comment]
> 在zotero中把标注文档中的颜色清理后就可用了，不知道什么原因

请问是清理哪个颜色？

**Comment by SimonJarry** [comment]
> > 在zotero中把标注文档中的颜色清理后就可用了，不知道什么原因
> 
> 请问是清理哪个颜色？

已经找到解决办法。把zotero笔记附件里的笔记（除级别标题外）全部选中并清除格式，再利用插件则可以生成笔记。

**Comment by DennisFriedl** [comment]
I have the same problem, It doesn't happen when I just annotate with the standard yellow color. The fix of deformating isn't really a fix for me because I want to keep the colors.

**Comment by SimonJarry** [comment]
> 我有同样的问题，当我只是用标准的黄色注释时，它不会发生。格式化的修复对我来说并不是真正的修复，因为我想保留颜色。

Hello, when I say notes, I mean the notes under the attachments to the articles. The fields in the template correspond to < it-notes >. At present, the note can be correctly generated only by clearing the content style. If you want to keep the colors, refer to the note template in the other questions.

**Comment by Postroggy** [comment]
@appwcn  想问一下，怎么打开笔记的源代码呀？note不是存储在 sqlite 里面吗？没看到入口

**Comment by aidenlx** [comment]
This was the same "renderColored" crash reported in several threads here. v2's markdown converter handles colored text and highlights directly, so it shouldn't come up anymore.

v2 beta is available now: https://zotlit.aidenlx.site/docs/install-zotlit
Migration guide: https://zotlit.aidenlx.site/docs/how-to/migrate-from-v1
