### ISSUE TITLE
Notes are not displayed

### ISSUE THREAD

**Issue by asan-emirsaleh** [PKM-er/obsidian-zotlit#311]
Hello!
I have recently encountered an interesting issue: While processing references with notes, no notes appear in the json schema under the "notes" field.

**Comment by asan-emirsaleh** [comment]
Update: I have checked the `zotero.sqlite`. It does content notes. And the schema did not changed in the most recent Zotero beta. But I noticed that there are different behaviors in different setups:
- the latest Obsidian, Zotero v7.0.0-beta.54+6b996d4f9: Notes are  available for Zotlit and could be rendered in md.
- the latest Obsidian and the latest Zotero: Notes are not available for Zotlit, and the "notes" field in the template editor is represented by an empty array.
![Screenshot from 2024-02-18 13-03-58](https://github.com/PKM-er/obsidian-zotlit/assets/23747850/57c2bd31-6b2f-45cc-aaa6-416dc3633b9f)
The other fields but "notes" possess data in the JSON schema inside the template editor.

**Comment by asan-emirsaleh** [comment]
The issue seems to be related to https://github.com/PKM-er/obsidian-zotlit/issues/272
![Screenshot from 2024-02-26 17-24-54](https://github.com/PKM-er/obsidian-zotlit/assets/23747850/b3225f1a-5d99-4c8e-ab90-8d6f1fa04111)
I have a note with some highlights coloured using Zotero-provided colour highlighting feature. This is possibly the cause of the error in notes schema constructing:
![Screenshot from 2024-02-26 17-21-38](https://github.com/PKM-er/obsidian-zotlit/assets/23747850/72aed28d-d90a-44d7-8766-99fd1e878b68)
```
plugin:zotlit:359 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'renderColored')
    at Object.replacement (plugin:zotlit:359:37939)
    at k.D (turndown.js:2:9551)
    at turndown.js:2:9210
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9059)
    at k.D (turndown.js:2:9459)
    at turndown.js:2:9210
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9059)
    at k.D (turndown.js:2:9459)
replacement @ plugin:zotlit:359
D @ turndown.js:2
(anonymous) @ turndown.js:2
b @ turndown.js:2
D @ turndown.js:2
(anonymous) @ turndown.js:2
b @ turndown.js:2
D @ turndown.js:2
(anonymous) @ turndown.js:2
b @ turndown.js:2
D @ turndown.js:2
(anonymous) @ turndown.js:2
b @ turndown.js:2
turndown @ turndown.js:2
turndown @ plugin:zotlit:359
normalizeNotes @ plugin:zotlit:359
eval @ plugin:zotlit:350
```

**Comment by asan-emirsaleh** [comment]
After I deleted colour markup from my notes, "notes" field in template editor worked normally. Lit note was also created normally.
I suggest such coloured highlights processing is to be considered as a #bug @aidenlx

**Comment by appwcn** [comment]
same issue here.

**Comment by appwcn** [comment]
与 https://github.com/PKM-er/obsidian-zotlit/issues/321 是同一个问题。希望作者能够修复…

**Comment by williamium3000** [comment]
seems like note is available now, do anyone know how to import the notes?

A related [issue](https://github.com/PKM-er/obsidian-zotlit/issues/402)

**Comment by aidenlx** [comment]
Your child notes now show up in templates through `zt.notes`, instead of the empty list you were seeing. There's also a new Template Data Explorer where you can browse exactly what data is available, including notes, before you write your template.

v2 beta is available now: https://zotlit.aidenlx.site/docs/install-zotlit
Migration guide: https://zotlit.aidenlx.site/docs/how-to/migrate-from-v1
