### ISSUE TITLE
Zotlit无法在Obsidian中创建文件

### ISSUE THREAD

**Issue by 930804783** [PKM-er/obsidian-zotlit#389]
plugin:zotlit:361 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'renderColored')
    at Object.replacement (plugin:zotlit:361:37275)
    at k.D (turndown.js:2:9551)
    at turndown.js:2:9210
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9059)
    at k.D (turndown.js:2:9459)
    at turndown.js:2:9210
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9059)
    at k.D (turndown.js:2:9459)

**Comment by 930804783** [comment]
这是控制台的代码，点完创建后无反应

**Comment by 3217333857** [comment]
> 这是控制台的代码，点完创建后无反应

同样的问题，请问怎么解决的

**Comment by edalatfard** [comment]
i have a same issue
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'renderColored')
    at Object.replacement (plugin:zotlit:361:37644)
    at k.D (turndown.js:2:9605)
    at turndown.js:2:9264
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9113)
    at k.D (turndown.js:2:9513)
    at turndown.js:2:9264
    at NodeList.reduce (<anonymous>)
    at k.b (turndown.js:2:9113)
    at k.D (turndown.js:2:9513)

**Comment by aidenlx** [comment]
这也是影响了不少用户的「renderColored」崩溃问题。v2 的笔记转换器已经完全不依赖该方法了，点击创建后应该可以正常生成笔记，不会再在控制台中静默报错了。

v2 beta 现已发布：https://zotlit.aidenlx.site/docs/install-zotlit
迁移指南：https://zotlit.aidenlx.site/docs/how-to/migrate-from-v1
